add extendPool
elysia-dev/elyfi-stakingpool-v2 pull request #14
Opened 2022-04-13 12:42 UTC by sujine2

Admin can change rewardPerSecondManually - add extendPool function

- Admin can set rewardPerSecond
- Admin can set duration
- As soon as the administrator calls the extendPool function, the information related reward is changed
- Rewards should be sent in the contract in advance

2022-04-14 07:52 UTC, jaeboklee-modo requested changes

2022-04-14 07:52 UTC, jaeboklee-modo commented on test/claim.test.ts
> +    it('rewardPerSecond is changed and stake and claim', async () => {
I'm not quite clear what the purpose of this test case. I think it's ok to be separated.

2022-04-14 07:52 UTC, jaeboklee-modo commented on test/stake.test.ts
>        await testEnv.rewardAsset.connect(deployer).faucet();
The `faucet` and `approve` processes appear in every context. How about putting these snippets in the top hooks of its file to reduce duplicates?

2022-04-14 07:52 UTC, jaeboklee-modo commented on test/withdraw.test.ts
> +      it('rewardPerSecond is changed and stake and withdraw', async () => {
I understand why you take expectedPoolData_1 and expectedUserData_1 as a parameter in expectedDataAfterStake, but I don't think that expectedDataAfterWithdraw takes the `expected User, Pool Data` former function does. 
I think If the intent was to check the scenario in which the user stakes, withdraws, and then claims, the `expectedAfter` function's parameter should be actual contract data.

2022-04-14 08:09 UTC, qpzm commented on test/claim.test.ts
> +      const tx = await testEnv.stakingPool.connect(deployer).extendPool(rewardPersecond, duration);
Actually rewardPerSecond is not changed.

2022-04-14 08:11 UTC, qpzm commented on test/utils/expect.ts
> +  );
This changes the `userIndex`, but `extendPool` does not change the `userIndex`.

2022-04-14 08:13 UTC, qpzm commented on test/settings.test.ts
> +  context('reset the pool', async () => {
We also need to check the rewardPerSecond, startTimestamp, endTimestamp are changed as we want.

2022-04-15 13:08 UTC, qpzm approved these changes

2022-04-15 13:09 UTC, merged